@startuml
abstract class PostalDelivery {
    +send(contents:String)
    {abstract} +createPackage(contents:String) : Package
}

class LetterDelivery extends PostalDelivery {
    +createPackage(contents:String) : Letter
}

class ParcelDelivery extends PostalDelivery {
    +createPackage(contents:String) : Parcel
}

interface Container
class Letter extends Container
class Parcel extends Container

@enduml